In [8]:
import numpy as np

In [135]:
# 1)numpy                       array operations
# 2)pandas                      data manipulation and analysis
# 3)matplotlib and seaborn      graphical Analysis
# 4)sklearn                     Machine Learning Algorithms and Techniques
# 5)statsmodels                 Statistical analysis
# 6)scipy                       statistical analysis

In [137]:
j=[5,7,2,8,4,7]
j

[5, 7, 2, 8, 4, 7]

In [139]:
d=np.array(j)
d

array([5, 7, 2, 8, 4, 7])

In [141]:
d.shape

(6,)

In [143]:
d.reshape(2,3)

array([[5, 7, 2],
       [8, 4, 7]])

In [145]:
d.size

6

In [147]:
d.ndim

1

In [149]:
s=[[4,8,9,12],[56,78,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]
s

[[4, 8, 9, 12],
 [56, 78, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [151]:
type(s)

list

In [153]:
a1=np.array(s)
a1

array([[ 4,  8,  9, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [155]:
a1.shape

(5, 4)

In [157]:
a1.size

20

In [171]:
a1.ndim

2

In [173]:
a1.reshape(2,10)

array([[ 4,  8,  9, 12, 56, 78, 54, 20, 67, 89],
       [50, 49, 77, 88, 22, 55, 90, 40, 70, 60]])

In [175]:
a1.ndim

2

In [177]:
arr2=[[4,8,9,2],[6,8,4,20],[7,8,50,4],[7,88,2,55],[9,4,7,60]]
arr2

[[4, 8, 9, 2], [6, 8, 4, 20], [7, 8, 50, 4], [7, 88, 2, 55], [9, 4, 7, 60]]

In [183]:
a2=np.array(arr2)
a2

array([[ 4,  8,  9,  2],
       [ 6,  8,  4, 20],
       [ 7,  8, 50,  4],
       [ 7, 88,  2, 55],
       [ 9,  4,  7, 60]])

In [185]:
a2.size

20

In [187]:
a2.ndim

2

In [193]:
z=a2.reshape(2,2,5)
z

array([[[ 4,  8,  9,  2,  6],
        [ 8,  4, 20,  7,  8]],

       [[50,  4,  7, 88,  2],
        [55,  9,  4,  7, 60]]])

In [195]:
z.ndim

3

In [211]:
ty=a2.reshape(1,1,2,5,2)
ty

array([[[[[ 4,  8],
          [ 9,  2],
          [ 6,  8],
          [ 4, 20],
          [ 7,  8]],

         [[50,  4],
          [ 7, 88],
          [ 2, 55],
          [ 9,  4],
          [ 7, 60]]]]])

In [213]:
ty.ndim

5

In [221]:
range(1,101,2)

range(1, 101, 2)

In [223]:
list(range(1,101,2))

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99]

In [229]:
tuple(range(1,101))

(1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100)

In [231]:
range(-100,0,1)

range(-100, 0)

In [237]:
tuple(range(-100,0,2))

(-100,
 -98,
 -96,
 -94,
 -92,
 -90,
 -88,
 -86,
 -84,
 -82,
 -80,
 -78,
 -76,
 -74,
 -72,
 -70,
 -68,
 -66,
 -64,
 -62,
 -60,
 -58,
 -56,
 -54,
 -52,
 -50,
 -48,
 -46,
 -44,
 -42,
 -40,
 -38,
 -36,
 -34,
 -32,
 -30,
 -28,
 -26,
 -24,
 -22,
 -20,
 -18,
 -16,
 -14,
 -12,
 -10,
 -8,
 -6,
 -4,
 -2)

In [239]:
range(2.5,5,0.5)


TypeError: 'float' object cannot be interpreted as an integer

In [243]:
np.arange(2.5,10,0.5)

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5,
       9. , 9.5])

In [249]:
for i in range(5,50,5):
    print(i)

5
10
15
20
25
30
35
40
45


In [251]:
l1=[5,10,15,20,25,30,35,40]
for i in l1:
    print(i)

5
10
15
20
25
30
35
40


In [267]:
j=[5,87,23,46,62,84,80,45,77,33,80]
even=[]
odd=[]
for i in j:
    if(j.index(i)%2==0):
        even.append(i)
    else:
        odd.append(i)
print(even)
print(odd)

[5, 23, 62, 80, 77, 80]
[87, 46, 84, 45, 33]


In [271]:
j=[5,87,23,46,62,84,80,45,77,33,80]
even=[]
odd=[]
for i in range(len(j)):
    if i%2==0:
        even.append(j[i])
    else:
        odd.append(j[i])
print(even)
print(odd)


[5, 23, 62, 80, 77, 80]
[87, 46, 84, 45, 33]
